version: '3.8'

services:

 seq:
    image: datalust/seq:latest
    ports:
        - 1403:80
    environment:
        ACCEPT_EULA: "Y"
        
 identity-api-sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: identity-api-db
    environment:
        SA_PASSWORD: "Password0!"
        ACCEPT_EULA: "Y"   
    ports: 
        - "1401:1433"

 identity-server:
    container_name: identity-server
    build: 
        context: ./src/Services/Identity/IdentityServer/
        dockerfile: ./Dockerfile
    ports: 
        - "1402:1402"

