version: '3.8'

services:

 seq:
    image: datalust/seq:latest
    ports:
        - 5341:80
    environment:
        ACCEPT_EULA: "Y"
        
 identity-api-sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
        - "1401:1433"
    # command: --init-file /database/identity-api-init.sql
    # volumes:
    #     - ./init.sql:/database/identity-api-init.sql
    environment:
        SA_PASSWORD: "Password0!"
        ACCEPT_EULA: "Y"
